export const REWARD_TYPES_MAP = {
  INVITATION_BONUS: "INVITATION BONUS",
  SIGNUP_BONUS: "SIGNUP BONUS",
  ATTENDANCE_BONUS: "ATTENDANCE BONUS",
  FIRST_RECHARGE_BONUS: "FIRST RECHARGE BONUS",
  DAILY_RECHARGE_BONUS: "DAILY RECHARGE BONUS",
  MEMBER_RECHARGE_COMMISSION: "MEMBER RECHARGE COMMISSION",
  FIRST_RECHARGE_AGENT_BONUS: "FIRST RECHARGE AGENT BONUS",
  DAILY_RECHARGE_AGENT_BONUS: "DAILY RECHARGE AGENT BONUS",
  VIP_LEVEL_UP_BONUS: "VIP LEVEL UP BONUS",
  VIP_MONTHLY_REWARD: "VIP MONTHLY REWARD",
  REFERRAL_BONUS: "REFERRAL BONUS",
  DAILY_SALARY: "DAILY SALARY",
  DAILY_TEAM_BONUS: "DAILY TEAM BONUS",
  DAILY_INTEREST: "DAILY INTEREST",
  EXTRA_SALARY: "EXTRA SALARY",
  GAME_LOSS_REFERRAL_BONUS: "GAME LOSS REFERRAL BONUS",
  REFERRAL_DEPOSIT_BONUS: "REFERRAL DEPOSIT BONUS",
};

export const REWARD_STATUS_TYPES_MAP = {
  SUCCESS: 1,
  LOCKED: 2,
};
